apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: post-service
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: post-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: app_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://post-service-mysql:3306/post_service
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
          image: trainingtexas/post-service:latest
          name: post-service
          ports:
            - containerPort: 8084
              protocol: TCP
      restartPolicy: Always
